"""Initial commit

Revision ID: 786380fcccc3
Revises: 
Create Date: 2021-12-14 20:19:16.405893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786380fcccc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('second_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_drivers_created_at'), 'drivers', ['created_at'], unique=False)
    op.create_table('vehichles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('plate_number', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_vehichles_created_at'), 'vehichles', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehichles_plate_number'), 'vehichles', ['plate_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehichles_plate_number'), table_name='vehichles')
    op.drop_index(op.f('ix_vehichles_created_at'), table_name='vehichles')
    op.drop_table('vehichles')
    op.drop_index(op.f('ix_drivers_created_at'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
